version: '3.7'

services:

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: mycalories
    ports:
      - "5433:5432"
    
  app:
    build: ./java
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
      
  client:
    build: ../fronted/
    ports:
      - "4001:80"
    depends_on:
      - app